[tool.poetry]
name = "utils"
version = "0.1.0"
description = "utils"
authors = ["Alon Fux <AlonFux@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymongo = "^4.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
